#-------------------------------
# General Site Settings
title: "Israel Ogbole"
description: "Thoughts on IoT and Cloud Computing"
logo: 'assets/images/logo.png'


#-------------------------------
# Author Settings
author:
  name: Israel 
  image: https://user-images.githubusercontent.com/2548160/103445496-98488300-4c6c-11eb-9d7e-7c02104a908e.png
  say-hello: Hello, I’m <strong>Israel Ogbole</strong>
  bio: I will use this space to share personal thoughts and experiences with Open Source Software, Raspberry Pi, Cloud-native technologies, and life in general. <br> Also, I will journal Naomi's programming journey here. Naomi is my nine-year-old daughter who loves coding.  

#-------------------------------
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle
twitter: https://twitter.com/israel_ogbole # Add your Twitter handle
linkedin: https://www.linkedin.com/in/israelo
github:  https://github.com/iogbole


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: disqus_npUAeUKkjE # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile:  # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-186535929-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: 'israelo.us7.list-manage.com/subscribe/post?u=53a3df9344e4aa53e567343bd&amp;id=6b55be21ac' # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
